### PR TITLE
feat: new message formats

### PR DESCRIPTION
**Pull request by cakarci**

### CODE REVIEW

**Review by cakarci — COMMENTED** [review]
test

**Review by pcakarci — COMMENTED** [review]
test

**Comment by pcakarci** [comment]
test

**Comment by pcakarci** [comment]
test12

**Review by pcakarci — CHANGES_REQUESTED** [review]
ytest

**Review by cakarci — COMMENTED** [review]
test

**Review by pcakarci — CHANGES_REQUESTED** [review]
test

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
dfd

**Review by scakarci — CHANGES_REQUESTED** [review]
tr

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
t

**Review by pcakarci — CHANGES_REQUESTED** [review]
c

**Review by scakarci — CHANGES_REQUESTED** [review]
xc

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — APPROVED** [review]

**Comment by cakarci** [comment]
test

**Comment by pcakarci** [comment]
test

**Pull request merged**
