### PR TITLE
feat: four eyes principle

### PR DESCRIPTION
**Pull request by cakarci**

### CODE REVIEW

**Review by pcakarci — CHANGES_REQUESTED** [review]
request changes 1

**Review by pcakarci — COMMENTED** [review]
commented

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — CHANGES_REQUESTED** [review]
change

**Review by scakarci — CHANGES_REQUESTED** [review]
againnnn

**Review by pcakarci — APPROVED** [review]
testtt

**Review by pcakarci — CHANGES_REQUESTED** [review]
request changes

**Review by scakarci — COMMENTED** [review]
dfg

**Review by scakarci — APPROVED** [review]

**Review by scakarci — APPROVED** [review]

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
dffegd

**Review by scakarci — APPROVED** [review]
dfg

**Review by pcakarci — COMMENTED** [review]
sdf

**Review by pcakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
dvbvd

**Review by scakarci — CHANGES_REQUESTED** [review]
dsf

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — COMMENTED** [review]
wdf

**Review by pcakarci — COMMENTED** [review]
test

**Review by pcakarci — APPROVED** [review]

**Pull request merged**
