### PR TITLE
feat: four eyes principle

### PR DESCRIPTION
**Pull request by cakarci**

### CODE REVIEW

**Review by pcakarci — COMMENTED** [review]
test

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — COMMENTED** [review]
aa

**Review by pcakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
add test

**Review by pcakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
test1

**Review by scakarci — COMMENTED** [review]
test

**Review by pcakarci — APPROVED** [review]
add test

**Review by scakarci — CHANGES_REQUESTED** [review]
asd

**Review by pcakarci — CHANGES_REQUESTED** [review]
test

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — CHANGES_REQUESTED** [review]
bb

**Review by pcakarci — CHANGES_REQUESTED** [review]
cc

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — CHANGES_REQUESTED** [review]
v

**Review by pcakarci — CHANGES_REQUESTED** [review]
n

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
dfbdfgdfg

**Review by scakarci — APPROVED** [review]
fcg

**Review by pcakarci — COMMENTED** [review]
test

**Review by pcakarci — COMMENTED** [review]
df

**Review by scakarci — COMMENTED** [review]
df

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — CHANGES_REQUESTED** [review]
j

**Review by pcakarci — CHANGES_REQUESTED** [review]
sdfds

**Review by pcakarci — CHANGES_REQUESTED** [review]
sdfg

**Review by pcakarci — CHANGES_REQUESTED** [review]
weres

**Review by scakarci — CHANGES_REQUESTED** [review]
fgnn

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — APPROVED** [review]

**Review by pcakarci — CHANGES_REQUESTED** [review]
change

**Review by pcakarci — CHANGES_REQUESTED** [review]
test12

**Review by pcakarci — CHANGES_REQUESTED** [review]
sdfsd

**Review by pcakarci — CHANGES_REQUESTED** [review]
sdfsfd

**Review by pcakarci — CHANGES_REQUESTED** [review]
xxxyyy

**Review by pcakarci — APPROVED** [review]

**Review by scakarci — APPROVED** [review]

**Review by pcakarci — COMMENTED** [review]
test

**Pull request closed without merging**
